version: '3.9'

services:
  website:
    #image: website-website:latest
    build:
      context: .
      dockerfile: dockerfile
      no_cache: true
    ports:
      - 80:80

# docker compose up -d --build