const FAQ = [
    {question:'¿Cómo puedo contactar con alguien de soporte?', answer: `Puedes contactarte con nosostros siguiendo <a href="#">este enlace</a>. Nuestro equipo está listo para ayudarte a través de WhatsApp, Email y Telegram.`},
    {question:'¿Cuánto tiempo demora en crearse mi servidor?', answer:'Después de hablar con nuestros agentes y seleccionar tu servidor, completaras el formulario que te enviaremos por mensaje privado. En minutos tu servidor estará listo.'},
    {question:'¿Cómo elijo el plan adecuado para mis necesidades?', answer:'Si tienes dudas sobre qué plan elegir, contáctanos directamente a través de <a href="#">este enlace</a> y te ayudaremos a elegir el adecuado para ti.'},
    {question:'¿Cuáles son las opciones de pago disponibles?', answer:'Aceptamos transferencias directas en pesos chilenos (CLP) si tienens cuenta bancaria en chile. También puedes pagar a través de PayPal en dólares (USD).'},
    {question:'¿Es posible aumentar los recursos de mi servidor después de la compra?', answer:'Sí, puedes aumentar los recursos de tu servidor y se te cobrará el proporcional de los recursos adicionales durante el resto de tiempo que queda de tu plan contratado.'},
    {question:'¿Es posible reducir los recursos de mi servidor después de la compra?', answer:'Sí, puedes reducirlos, pero no se realizará un reembolso por los recursos no utilizados.'},
    {question:'¿Es posible instalar plugins y mods en mi servidor de Minecraft?', answer:'Sí, una vez elijas una versión de Minecraft compatible con tus mods y/o plugins, puedes subir los archivos a la carpeta correspondiente en la sección de archivos del panel de administración de Pterodactyl. Si necesitas ayuda, contáctanos en nuestros canales de comunicación en <a href="#">este enlace</a>.'},
    {question:'Para Minecraft, ¿Puedo jugar con Bedrock y Java?', answer:'Sí, al seleccionar un servidor de Minecraft, elige la edición y luego la versión deseada. Si estás indeciso, contáctanos a través de <a href="#">este enlace</a> y te ayudaremos a elegir.'},
    {question:'Para Minecraft ¿Puedo subir mi propio mundo al servidor?', answer:'Sí, puedes conectarte por protocolo SFTP al servidor para subir los archivos de tu mundo de Minecraft. Si necesitas ayuda o no sabes cómo hacerlo, contáctanos en <a href="#">este enlace</a>.'},
    {question:'¿Es posible migrar mi servidor a Andes Hosting?', answer:'Sí, puedes conectarte por protocolo SFTP al servidor para subir los archivos de tu mundo de Minecraft. Si necesitas ayuda o no sabes cómo hacerlo, contáctanos en <a href="#">este enlace</a>.'}
]

export default FAQ